export const customerList = [
  {
    id: "10",
    title: "Chieko Chute",
    email: "chieko@mail.com",
    location: "Philadelphia, USA",
    orders: "125 orders",
    price: "$101,345.00",
  },
  {
    id: "11",
    title: "Annabel Rohan",
    email: "rohan_anna@mail.com",
    location: "Los Angeles, USA",
    orders: "11 orders",
    price: "$2,400.98",
  },
  {
    id: "12",
    title: "Pedro Huard",
    email: "pedrohuar@mail.com",
    location: "Manhattan, USA",
    orders: "98 orders",
    price: "$56,987.00",
  },
  {
    id: "13",
    title: "Jamel Eusebio",
    email: "eusebio234@mail.com",
    location: "Toronto, CA",
    orders: "51 orders",
    price: "$12,567.90",
  },
  {
    id: "14",
    title: "Augustina Midgett",
    email: "midgett245@mail.com",
    location: "Pittsburgh, USA",
    orders: "12 orders",
    price: "$101,345.00",
  },
  {
    id: "15",
    title: "Geoffrey Mott",
    email: "motgeoff@mail.com",
    location: "Montreal, CA",
    orders: "56 orders",
    price: "$4,670.44",
  },
];
